Fix poplar deprecation
onnela-lab/forest pull request #102
Opened 2022-04-15 20:57 UTC by clementzach

This fixes [this issue](https://github.com/onnela-lab/forest/issues/101#issue-1200686168) as well as implements PEP8 and static type checking. I believe it is complete, but may add tests in the next few days if I have time.

2022-04-27 16:01 UTC, hackdna requested changes
Thanks! Yes, it would be great to add some tests.

2022-04-29 02:39 UTC, clementzach commented on forest/poplar/legacy/common_funcs.py
> +    stamp_end = 0.
Ah, it should be an int because it can be assigned as the output of datetime2stamp (an int)

2022-04-29 20:08 UTC, hackdna commented on forest/poplar/legacy/common_funcs.py
> +from typing import Optional, Any, List, Union
Looks like you forgot about pytz.

2022-04-29 20:33 UTC, hackdna requested changes

2022-04-29 20:33 UTC, hackdna commented on forest/poplar/legacy/tests/test_poplar_functions.py
> +    try:
[pytest.raises()](https://docs.pytest.org/en/stable/reference/reference.html?highlight=raises#pytest.raises) is what you need here. Also, there should be a separate test for each type of error.

2022-04-29 20:33 UTC, hackdna commented on forest/poplar/legacy/tests/test_poplar_functions.py
> +    print(timestamp_list)
There should be no output from a successful test run.

2022-05-02 22:05 UTC, hackdna approved these changes
Thank you!

2022-05-02 22:05 UTC, merged