Audio submits
onnela-lab/forest pull request #134
Opened 2022-09-17 23:06 UTC by clementzach

2022-09-19 19:34 UTC, hackdna requested changes
I've merged #119 but now this PR has conflicts with `develop`.

2022-09-22 19:19 UTC, hackdna requested changes

2022-09-22 19:19 UTC, hackdna commented on forest/sycamore/submits.py
> +    for q in survey_dict["content"]:
`q` -> `question`?

2022-09-22 19:19 UTC, hackdna commented on forest/sycamore/tests/test_functions.py
> +from forest.sycamore.submits import (gen_survey_schedule, get_question_ids,
utils after submits

2022-09-22 19:19 UTC, hackdna commented on forest/sycamore/tests/test_functions.py
> +from forest.sycamore.read_audio import (get_audio_survey_id_dict,
read_audio before responses

2022-09-22 19:19 UTC, hackdna commented on forest/sycamore/utils.py
> +        study_dir (str):  filepath to json file.
This is not actually a dir but a json file path, so the name should reflect that (e.g., `filepath`).

2022-09-22 19:19 UTC, hackdna commented on forest/sycamore/utils.py
> +        dictionary = json.load(f)
Simply: `return json.load(f)`?

2022-09-27 16:04 UTC, hackdna commented on forest/sycamore/utils.py
> +        dictionary = json.load(f)
You still need to open the file with a context manager to make sure the file is closed when processing is finished:
```python
with open(study_dir, "r") as f:
    return json.load(f)
```

2022-09-27 16:05 UTC, hackdna requested changes
Just one outstanding item I think.

2022-09-27 16:42 UTC, clementzach commented
Awesome, thank you so much!

2022-09-27 17:03 UTC, hackdna approved these changes

2022-09-27 17:05 UTC, merged