Add duration of audio surveys to sycamore
onnela-lab/forest pull request #139
Opened 2022-10-18 22:01 UTC by clementzach

This function adds the durations of audio surveys to sycamore.

2022-10-20 18:06 UTC, hackdna requested changes
Thanks!

2022-10-25 21:41 UTC, clementzach commented
@hackdna the main issue I'm dealing with is an error in the automated checks. I'm getting:
```
OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory
```

It seems that fixing this is [more complicated](https://stackoverflow.com/questions/57743005/how-to-use-soundfile-on-heroku) than just changing our requirements file. 

Do you know if there's an easy way to solve this, or does this mean that librosa is not "easy to install" and it shouldn't be included as a dependency for forest?

2022-10-29 12:52 UTC, clementzach commented
@hackdna thank you so much for figuring that out!

2022-11-01 16:09 UTC, hackdna requested changes
No problem. Also, please add instructions on how to install `librosa` dependencies in Linux to Sycamore docs: https://forest.beiwe.org/en/latest/sycamore.html

2022-11-01 16:09 UTC, hackdna commented on forest/sycamore/read_audio.py
> +import librosa  # type: ignore
We add modules with missing type hints to https://github.com/onnela-lab/forest/blob/develop/mypy.ini
More details: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

2023-01-09 23:15 UTC, clementzach commented
Sorry this slipped my mind, hopefully these changes are sufficient to get this merged before I move on

2023-01-10 16:28 UTC, merged