Update forest tutorial with mano, venv and forest updates
onnela-lab/forest pull request #161
Opened 2023-03-23 21:53 UTC by GeorgeEfstathiadis

2023-03-24 00:29 UTC, hackdna requested changes

2023-03-24 00:29 UTC, hackdna commented on tutorials/helper_functions.py
> +                num_tries = 6
Replace with:
```
else:
    break
```

2023-03-24 00:29 UTC, hackdna commented on tutorials/helper_functions.py
> +                num_tries = 6
`break`

2023-03-24 00:29 UTC, hackdna commented on tutorials/helper_functions.py
> +        num_tries = 1
`num_tries` = 0`?

2023-03-24 00:29 UTC, hackdna commented on tutorials/helper_functions.py
> +        while not download_success:
`while num_tries < 5:`?

2023-03-24 00:29 UTC, hackdna commented on tutorials/helper_functions.py
> +                download_success = True
`break`?

2023-03-24 00:29 UTC, hackdna commented on tutorials/helper_functions.py
> +                download_success = True
`break`?

2023-03-24 00:29 UTC, hackdna commented on tutorials/helper_functions.py
> +                download_success = True
`break`?

2023-03-24 00:29 UTC, hackdna commented on tutorials/keyring_studies.py
Since this only sets shell env vars, should that just be a shell script?

2023-03-24 21:32 UTC, GeorgeEfstathiadis commented on tutorials/keyring_studies.py
So I added the shell script that replaces `keyring_studies.py`, but I am unsure how to run it from jupyter notebook and have it access the environment variables from the notebook. I tried simply `!beiwe_credentials.sh` and I have set up its access to be executable by everyone, but yet I don't seem to be able to access the environment variables that way.

2023-03-28 16:40 UTC, hackdna commented on tutorials/keyring_studies.py
I see. Running a shell script in a notebook happens in a subprocess, so changes to env vars won't be reflected in the notebook itself. I guess in this case it's fine to have a Python script, or may be use `%env`?
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-env

2023-03-28 16:51 UTC, hackdna requested changes
Thanks!

2023-03-28 16:51 UTC, hackdna commented on tutorials/helper_functions.py
> +        os.makedirs(download_folder, exist_ok=True)
The point of `exist_ok=True` is that you don't need to check if a directory exists.
https://docs.python.org/3.8/library/os.html#os.makedirs

2023-03-28 16:51 UTC, hackdna commented on tutorials/helper_functions.py
> +                break
```
else:
    break
```
https://docs.python.org/3/reference/compound_stmts.html#except

2023-03-28 16:51 UTC, hackdna commented on tutorials/helper_functions.py
> +                break
```
else:
    break
```
https://docs.python.org/3/reference/compound_stmts.html#except

2023-03-28 16:51 UTC, hackdna commented on tutorials/helper_functions.py
> +        if num_tries == 5:
I think while-else clause would be more readable
https://realpython.com/lessons/while-loop-else-clause/

2023-03-30 10:13 UTC, GeorgeEfstathiadis commented on tutorials/keyring_studies.py
I am not sure how to use the `%env` magic to set environment variables that are hidden in the script.

2023-03-30 10:14 UTC, GeorgeEfstathiadis commented on tutorials/keyring_studies.py
because we want the actual variable values to be set in a separate place to share between scripts

2023-03-30 14:21 UTC, hackdna approved these changes
Thank you!

2023-03-30 14:21 UTC, merged