Jasmine physical cyrcadian rhythm
onnela-lab/forest pull request #205
Opened 2023-10-16 19:33 UTC by GeorgeEfstathiadis

* add physical cyrcadian rhythm and stratified physical cyrcadian rhythm columns
* move rarely-used parameters to `Hyperparameters` class to reduce parameters used in `gps_stats_main`

2023-10-17 19:41 UTC, hackdna requested changes
Also, `gps_summaries()` is ~700 lines of code right now. Is there a way to simplify or refactor?

2023-10-17 19:41 UTC, hackdna commented on docs/source/jasmine.md
> +When using jasmine, you should call function `gps_stats_main(study_folder, output_folder, tz_str, frequency, save_traj, places_of_interest = None, osm_tags = None, time_start = None, time_end = None,
Lowercase: `all_bv_set`

2023-10-17 19:41 UTC, hackdna commented on docs/source/jasmine.md
>     - `all_memory_dict` and `all_BV_set` are dictionaries from previous run (none if it's the first time).
Lowercase: `all_bv_set`

2023-10-17 19:41 UTC, hackdna commented on docs/source/jasmine.md
> +- `Hyperparameters`: @dataclass to store the hyperparameters for the imputation and summary statistics.
Does `@` have a special meaning here?

2023-10-17 19:41 UTC, hackdna commented on forest/jasmine/tests/test_traj2stats.py
> +                                       Hyperparameters, gps_summaries)
Imports should be in alphabetical order

2023-10-17 19:41 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +from datetime import datetime
The `datetime` module is part of the standard library, so should be in the block above
https://docs.python.org/3.8/library/datetime.html

2023-10-17 19:41 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    pcr_sample_rate = parameters.pcr_sample_rate
Are these re-assignments necessary?

2023-10-17 19:41 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        # mobility trace
Comments should explain the code or should be removed.

2023-10-17 19:41 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +            # physical cyrcadian rhythm
circadian

2023-10-17 19:41 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                    (start_time, end_time), mobility_trace,
`mobility_trace` might be referenced before assignment

2023-10-18 18:17 UTC, hackdna requested changes
Thanks! Also, would it make sense to add some unit tests for the new functions?

2023-10-18 18:17 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                            parameters, ids, locations, ids_keys_list
`ids_keys_list` might be referenced before assignment

2023-10-18 18:17 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        summary_stats_df2: pandas dataframe with summary statistics
No need to mention returned variable name since it is not a part of the API.
https://google.github.io/styleguide/pyguide.html#doc-function-returns

2023-10-18 18:17 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        end_stamp: int, ending time stamp
"Do not imitate older ‘NumPy style’ ([example](https://numpy.org/doc/1.24/reference/generated/numpy.linalg.qr.html)), which frequently documented a tuple return value as if it were multiple return values with individual names (never mentioning the tuple). Instead, describe such a return value as: “Returns: A tuple (mat_a, mat_b), where mat_a is …, and …”.
https://google.github.io/styleguide/pyguide.html#doc-function-returns

2023-10-18 18:17 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        no_windows: int, number of windows
"Do not imitate older ‘NumPy style’ ([example](https://numpy.org/doc/1.24/reference/generated/numpy.linalg.qr.html)), which frequently documented a tuple return value as if it were multiple return values with individual names (never mentioning the tuple). Instead, describe such a return value as: “Returns: A tuple (mat_a, mat_b), where mat_a is …, and …”.
https://google.github.io/styleguide/pyguide.html#doc-function-returns

2023-10-18 18:17 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    no_windows = (end_stamp - start_stamp) // window
Typical abbreviation of "number of" is "num", so `num_windows`

2023-10-18 18:17 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +def compute_window_and_windows_count(
simply `compute_window_and_count()`?

2023-10-19 14:05 UTC, GeorgeEfstathiadis commented on forest/jasmine/traj2stats.py
> +    return circle, saved_polygons
we also need the `loc_str` to access the element from `saved_polygons`, how do you propose we do it differently?

2023-10-20 17:54 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    return circle, saved_polygons
OK, I missed that part.

2023-10-20 18:06 UTC, hackdna requested changes
Thanks!

2023-10-20 18:06 UTC, hackdna commented on forest/jasmine/tests/test_traj2stats.py
> +def test_compute_window_and_count_window(sample_trajectory):
`test_compute_window_size`?

2023-10-20 18:06 UTC, hackdna commented on forest/jasmine/tests/test_traj2stats.py
> +def test_compute_window_and_count_num_windows(sample_trajectory):
`test_compute_window_count`?

2023-10-20 18:06 UTC, hackdna commented on forest/jasmine/tests/test_traj2stats.py
> +def test_compute_window_and_count_window2(sample_trajectory):
`test_compute_window_size_6_hour`?

2023-10-20 18:06 UTC, hackdna commented on forest/jasmine/tests/test_traj2stats.py
> +def test_compute_window_and_count_num_windows2(sample_trajectory):
`test_compute_window_count_6_hour`?

2023-10-30 19:26 UTC, hackdna approved these changes
Thank you!

2023-10-30 19:32 UTC, merged