Added transform_point_to_circle
onnela-lab/forest pull request #54
Opened 2021-12-03 18:26 UTC by GeorgeEfstathiadis

Added function to transform a center point to a shapely circus with a given radius.

2021-12-03 18:28 UTC, GeorgeEfstathiadis commented
Sorry about that, but I am failing on `mypy` again. Do I add the modules in the `setup.py` and `requirements.txt` to pass the checks?

2021-12-08 15:42 UTC, hackdna requested changes
Yes, you need to add Forest dependencies to `requires` list in `setup.py` (alphabetical order). Only dev dependencies go into `requirements.txt`.

2021-12-08 15:42 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +def transform_point_to_circle(coords: Tuple[float, float], radius: int
If `coords` has to be unpacked anyway then it makes sense to pass `lat` and `lon` directly instead.

2021-12-08 15:42 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    circle_poly = transform(aeqd_to_wgs84, buffer)
No need for `circle_poly` variable, simply return here?

2021-12-08 15:42 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +import time
Unused module?

2021-12-08 15:42 UTC, hackdna commented on forest/jasmine/tests/test_traj2stats.py
> +    )
This statement can fit on one line

2021-12-09 10:15 UTC, GeorgeEfstathiadis commented
Still no luck with mypy failing.

2021-12-09 20:25 UTC, hackdna requested changes
The mypy error message references several possible solutions: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

In this case the only way to solve this is to suppress this error for `shapely` because no type annotations for it exist. This is accomplished by adding the following section (in alphabetical order) to `mypy.ini`:
```
[mypy-shapely.*]
ignore_missing_imports = True
```

2021-12-09 20:25 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +from typing import Tuple
Unused import?

2021-12-10 19:48 UTC, hackdna approved these changes

2021-12-10 19:49 UTC, merged