added get_nearby_locations function
onnela-lab/forest pull request #57
Opened 2021-12-13 14:37 UTC by GeorgeEfstathiadis

Added function to extract nearby locations using Openstreetmaps api from trajectories numpy array.

2021-12-13 14:47 UTC, GeorgeEfstathiadis commented
I don't understand why it says that `great_circle_dist` has too many arguments, since it takes 4 and I provide it 4 in `great_circle_dist(*row[1:3], lat[i], lon[i])`.

2021-12-13 19:49 UTC, hackdna requested changes

2021-12-13 19:49 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                         ) -> Tuple[dict, dict, dict]:
This statement can fit on one line

2021-12-13 19:49 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +            lon.append(row[2])
I think this conditional can be much easier to read by doing something like:
```
distance = np.min([...])
if len(lat) == 0 or distance > 1000
    ...
```
It'd be also great to explain what does `len(lat) == 0` mean

2021-12-13 19:49 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    lon: List[float] = []
I'd name these variables something like `latitudes` and `longitudes` for readability since they are lists.

2021-12-13 19:49 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        bbox = bounding_box((lat[i], lon[i]), 1000)
This can be more pythonic:
```
for lat, lon in zip(latitudes, longitudes):
    bounding_box(lat, lon, ...)
```

2021-12-13 19:49 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        nearby_locations_coord: dictionary, nearby locations' coordinates
Should this be location tags?

2021-12-13 19:57 UTC, hackdna commented
Could you write a test for `great_circle_dist(*row[1:3], lat[i], lon[i])` to confirm the actual number of values passed in?

2021-12-13 20:02 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                        for i in range(len(lat))
You can also use the `zip()` here instead.

2021-12-13 21:55 UTC, hackdna commented
This also may be a limitation of mypy since `great_circle_dist(lat[i], lon[i], *row[1:3])` produces no error. So, perhaps the best (and potentially more readable) solution is to unpack `row[1:3]` before passing the values to the function.

2021-12-15 16:44 UTC, hackdna approved these changes
Thank you very much!

2021-12-15 16:45 UTC, merged