gps_summaries places of interest feature
onnela-lab/forest pull request #60
Opened 2022-01-13 09:58 UTC by GeorgeEfstathiadis

Update gps_summaries function in jasmine with additional features.

Sorry for the long pull request, but most of it is just reformatting for PEP8 and line length of the function.

2022-01-13 22:20 UTC, hackdna requested changes

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                    start_temp = [0, stop2]
`stop2` might be referenced before assignment

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                    end_temp = [stop1, -1]
`stop1` might be referenced before assignment

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                        for element_id in ids[place]:
`ids` might be referenced before assignment

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                            if len(locations[element_id]) == 1:
`localtions` might be referenced before assignment

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                        all_place_times[-1] += row[2] / 60
`all_place_times` might be referenced before assignment

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                            all_place_times_adjusted[h] += (
`all_place_times_adjusted` might be referenced before assignment

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                        for location_index, _ in enumerate(locations.keys()):
something like `for place_id, places in locations:`?

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                                    log_tags_temp.append(tags[element_id])
`tags` might be referenced before assignment

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                D = pairwise_great_circle_dist(temp[:, [1, 2]])
`D` should be lowercase and ideally something more descriptive

2022-01-13 22:20 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        summary_stats_df_datetime = summary_stats_df[::2].reset_index(
`summary_stats_df` might be referenced before assignment

2022-01-13 22:29 UTC, hackdna commented
Thanks for the PR! The reason `gps_summaries()` is difficult to test is that it is doing too much. It's about 700 lines long and has complex logic. If you could break it down into smaller pieces they'd be easier to test. Also, it might be useful to come up with a small, subsampled dataset just for testing.

2022-01-13 22:46 UTC, hackdna commented
And this should help you resolve merge conflicts: https://github.com/onnela-lab/forest/commit/8dea5ed987d5f7782a59712b0d6d23ca2fd2d488

2022-01-14 11:55 UTC, GeorgeEfstathiadis commented
Ok, I will try to think about how to separate it into multiple functions and some kind of subsampled dataset.

2022-01-14 17:30 UTC, hackdna commented
Thanks! If this function ends up too difficult to refactor, just having a tiny dataset for testing would be great. It doesn't have to be scientifically meaningful (that part can be verified outside the unit test suite), as long as it helps to exercise the code logic and to show what the data structures look like.

2022-01-14 19:39 UTC, hackdna requested changes

2022-01-14 19:39 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    if option not in ["hourly", "daily"]:
Would it make sense to make `option` an enum? Then this check would not be necessary. Also, may be rename it to something like `frequency`?

2022-01-14 19:39 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        end_time2 = 0
I think it would make the code more readable if these two definitions are moved to where `start_time` and `end_time` are defined.

2022-01-14 19:39 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +            for _, row in enumerate(pause_array):
Simplify with something like `for pause in pause_array`?

2022-01-14 19:39 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                    all_place_probs = [
`all_place_probs = [0] * len(places_of_interest)`
or
`all_place_probs = np.zeros_like(places_of_interest)`?

2022-01-18 21:38 UTC, hackdna requested changes
Thanks, sounds good. Just a few more issues.

2022-01-18 21:38 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +            res = [year, month, day] + [0 for _ in range(18)]
`res = [year, month, day] + [0] * 18`? Also, it'd be great to explain what 18 is.

2022-01-18 21:38 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                res += [0 for _ in range(2 * len(places_of_interest) + 1)]
`res += [0] * (2 * len(places_of_interest) + 1)`?

2022-01-18 21:38 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                    res += all_place_times
`all_place_times` might be referenced before assignment

2022-01-18 21:38 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                    res += all_place_times_adjusted
`all_place_times` might be referenced before assignment

2022-01-18 21:38 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                log_tags[f"{day}/{month}/{year} {hour}:00"] = log_tags_temp
`log_tags_temp` might be referenced before assignment

2022-01-18 21:38 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        summary_stats_df = pd.DataFrame(np.array(summary_stats))
No need for `np.array` here. See 8dea5ed.

2022-01-18 21:38 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        summary_stats_df_datetime = summary_stats_df[::2].reset_index(
Still a potential issue

2022-01-19 21:22 UTC, hackdna requested changes

2022-01-19 21:22 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        option: Frequency class
Should be something like `frequency: how often summary statistics are calculated`?

2022-01-19 21:22 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                # datetime
daytime?

2022-01-19 21:22 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                # for datetime/nighttime + other
daytime?

2022-01-19 21:22 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                    all_place_probs = [
Did this fix get reverted by accident?

2022-01-20 19:49 UTC, hackdna approved these changes
Thank you very much!

2022-01-20 19:49 UTC, merged