Update gps_stats_main for new features
onnela-lab/forest pull request #69
Opened 2022-01-25 17:44 UTC by GeorgeEfstathiadis

Updating `gps_stats_main` function in format for better readability and adhering to PEP8 as well as to accommodate the new features added in the summary statistics.

2022-01-25 19:48 UTC, hackdna requested changes

2022-01-25 19:48 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                            ) as loc:
If a statement can fit on one line then spreading it across multiple lines actually hurts readability.

2022-01-25 19:48 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    if parameters is None:
Would it make sense to make `parameters` a dataclass?
https://docs.python.org/3.8/library/dataclasses.html

2022-01-26 14:58 UTC, GeorgeEfstathiadis commented on forest/jasmine/traj2stats.py
> -    quality_threshold = quality_threshold if quality_threshold is not None else 0.05
I see I think this parameter did not exist when I was making the new features, that is probably why I discarded it by accident.

2022-01-26 15:33 UTC, GeorgeEfstathiadis commented on forest/jasmine/traj2stats.py
> +    ] = parameters
I don't know exactly what they are and I gave a quick look at the functions they are used and there is not a clear description of what they do. I described on the data-class that they are hyper-parameters and for which functions they are used.

2022-01-26 17:51 UTC, hackdna requested changes
Thank you, just a few more items.

2022-01-26 17:51 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        quality_threshold = 0.05
Simply provide a default value in the function signature?

2022-01-26 17:51 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    if parameters.h is None:
I think the three above conditionals are not necessary given the three preceding assignments?

2022-01-26 17:51 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        for id_code in beiwe_study_ids:
Would something like `study_id` be more readable than `id_code`?

2022-01-26 17:51 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    parameters: Hyperparameters,
This should have a default value of `None` here. Then you can assign a value of `Hyperparameters()` in the body of the function if not provided by the caller (just like you did for `quality_threshold` except that value is not mutable so does not need special treatment).

See mutable default arguments for details: https://docs.python-guide.org/writing/gotchas/

2022-01-26 21:10 UTC, hackdna requested changes

2022-01-26 21:10 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +    if len(beiwe_study_ids) > 0:
I think this line is redundant so can be removed. This will also free up some line space in the code below when the for loop is shifted left.

2022-01-26 22:24 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +        for study_id in participant_ids:
`study_id` -> `participant_id`

2022-01-26 22:51 UTC, hackdna commented
Also, are you planning to update the README in a separate PR?

2022-01-27 11:05 UTC, GeorgeEfstathiadis commented
Yes I was planning to do it on separate PR to update the instructions for using both Bonsai and Jasmine and then that should be it.

2022-01-27 15:33 UTC, hackdna approved these changes
Thank you very much!

2022-01-27 15:34 UTC, merged