Add dictionary to store transformed polygons
onnela-lab/forest pull request #79
Opened 2022-02-05 14:22 UTC by GeorgeEfstathiadis

Any circle that is created is stored for later use if needed again, instead of running the `transform_point_to_circle` multiple times.

Closes #78

2022-02-05 14:25 UTC, GeorgeEfstathiadis commented
I used `cProfile` to find where the code was slow and found that indeed the code was running the `transform_point_to_circle`  function significantly and it was spending most of its time there. Now when running it again it seems to have reduced the runtime by 4-5 times and `transform_point_to_circle` is getting run significantly less times.

2022-02-07 21:31 UTC, hackdna requested changes
Thanks, this is a huge performance improvement!

2022-02-07 21:31 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                        f"{pause[0]}, {pause[1]} - person"
Could you make this a variable? I think it would make the code less repetitive and more readable.

2022-02-07 21:31 UTC, hackdna commented on forest/jasmine/traj2stats.py
> +                                    f"{loc_lat}, {loc_lon} - place"
Could you make this a variable? I think it would make the code less repetitive and more readable.

2022-02-08 15:07 UTC, hackdna approved these changes
Thank you!

2022-02-08 15:07 UTC, merged